# Generated by Django 4.1.7 on 2023-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mode', '0008_ordendepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='pruebas', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut',
            field=models.CharField(default='pruebas', max_length=20),
        ),
    ]
