# Generated by Django 4.1.7 on 2023-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mode', '0009_reserva_nombre_reserva_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
